### PR TITLE
Linked list examp

### PR DESCRIPTION
**Pull request by DevinR528**
I thought this example might highlight a cool use case? This did not seem possible with the new macro unfortunately.

### CODE REVIEW

**Comment by whatisaphone** [comment]
Thanks, this is great!

Can you add the lint attributes from the other top-level modules? (i.e. [these 3 lines](https://github.com/whatisaphone/genawaiter/blob/8d9416b4bc9d7906ed5280d090d970bb15cc45ba/examples/error_propagation/src/main.rs#L8-L10))

**Comment by DevinR528** [comment]
In the future would you want me to merge something like the `syn` feature addition, if so what is your preferred git sequence. It looks like you rebase, considering you had to force push? Is something like the example since you reviewed it ok for me to merge?

**Comment by whatisaphone** [comment]
Sorry for the delay, this must have gotten lost in my email!

Reading this closer there's a couple things I'd want to change. Generally I think we should model the actual list implementation after the famous Learn Rust With Entirely Too Many Linked Lists book, specifically the [Ok Stack](https://rust-unofficial.github.io/too-many-lists/second-final.html). Reason being, by giving things standard names and simpler logic, it will become easier to follow the example. Sorry it's a nitpicky request and a bit of a vague description, I can list some specific changes if you want or I'm even happy to make the changes myself. The biggest one that stands out is rename insert->push and take out that loop (linked lists traditionally prepend when you add items since prepending is O(1))

<details>
<summary>Also, I was able to get it working with the new macro</summary>

```rust
    fn iter(&self) -> impl Iterator<Item = &T> {
        let mut current = &self.next;
        gen!({
            while let Child::Next { next, val } = current {
                yield_!(val);
                current = &*next;
            }
        })
        .into_iter()
    }
```

</details>

For things like the `syn` change, I'd like to review them, only to follow the principle of multiple sets of eyes. And also because I learned something from even just that one-line PR (specifically, syn's "full" feature doesn't include the whole library the way most libs e.g. tokio's "full" feature does) and I'd like to continue reading and learning from your code!

Re: git workflow, I checked out that PR locally to test, then rebased locally, then pushed normally. I'm not sure why GitHub counted it as a force push /shrug

**Comment by DevinR528** [comment]
All That makes total sense! With so many people using and checkout the project it makes it important to keep it standard I'll just do a bit of copy paste update dancing! I am very familiar with that example, every time while learning I was trying to write a more complicated iterator one would inevitably find themselves there.

I'm glad you got it working with the macro that's even shorter and cleaner

**Comment by DevinR528** [comment]
ahh sorry to spam your email with all these pushes and test runs I finally got it

**Comment by whatisaphone** [comment]
This is perfect, thanks for writing this example!

**Pull request merged**
